---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
  labels:
    app: shopping
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shopping
      version: v1.0
  template:
    metadata:
      labels:
        app: shopping
        version: v1.0
    spec:
      containers:
      - name: shopping
        image: xylene1980/shopping:v1
        ports:
        - name: http
          containerPort: 5000
